// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AhoCorasickSearchList
Rcpp::List AhoCorasickSearchList(Rcpp::StringVector keywords, Rcpp::List textList, std::string alphabet, bool groupByKeyword);
RcppExport SEXP AhoCorasickTrie_AhoCorasickSearchList(SEXP keywordsSEXP, SEXP textListSEXP, SEXP alphabetSEXP, SEXP groupByKeywordSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type keywords(keywordsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type textList(textListSEXP);
    Rcpp::traits::input_parameter< std::string >::type alphabet(alphabetSEXP);
    Rcpp::traits::input_parameter< bool >::type groupByKeyword(groupByKeywordSEXP);
    __result = Rcpp::wrap(AhoCorasickSearchList(keywords, textList, alphabet, groupByKeyword));
    return __result;
END_RCPP
}
// AhoCorasickSearch
Rcpp::List AhoCorasickSearch(Rcpp::StringVector keywords, Rcpp::StringVector text, std::string alphabet, bool groupByKeyword);
RcppExport SEXP AhoCorasickTrie_AhoCorasickSearch(SEXP keywordsSEXP, SEXP textSEXP, SEXP alphabetSEXP, SEXP groupByKeywordSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type keywords(keywordsSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type text(textSEXP);
    Rcpp::traits::input_parameter< std::string >::type alphabet(alphabetSEXP);
    Rcpp::traits::input_parameter< bool >::type groupByKeyword(groupByKeywordSEXP);
    __result = Rcpp::wrap(AhoCorasickSearch(keywords, text, alphabet, groupByKeyword));
    return __result;
END_RCPP
}
